### ISSUE TITLE
Need more disk space

### ISSUE THREAD

**Issue by b1conrad** [Picolab/Manifold-production-instance#1]
because we keep running out of space, and at 100% utilization the pico-engine stops.

**Comment by windley** [comment]
I've doubled the disk space on the volume. 

It may or may not actually double on the machine without further intervention at the OS leve. 

Please monitor and see.

**Comment by b1conrad** [comment]
The OS is not yet showing the doubling, so some intervention is necessary. The pico-engine is backed-up as of now
