### ISSUE TITLE
google application_id should be secret?

### ISSUE THREAD

**Issue by b1conrad** [Picolab/Manifold-production-instance#2]
In the ruleset `io.picolabs.google_signin` there is an APPLICATION_ID which is checked in to the Manifold repo. Is this a key that should be kept to us?

**Comment by nmartinezbyu** [comment]
After some research it has been found that "The client ID is considered public information, and is used to build login URLs, or included in Javascript source code on a page. The client secret must be kept confidential." The APPLICATION_ID is the Manifold Google Client ID.

**Comment by nmartinezbyu** [comment]
Moving over to review.

**Comment by b1conrad** [comment]
Thanks, Beto!
