### ISSUE TITLE
Manifold Aries agents cannot interoperate with agents outside of the production instance

### ISSUE THREAD

**Issue by b1conrad** [Picolab/Manifold-production-instance#6]
There is a problem with `meta:host` in Manifold, which is set to http://10.0.0.220:8080 but that only works for other agents running in our local network! 

This appears in the connections invitation, and it should instead be https://manifold.picolabs.io:9090 which is usable throughout the Internet for the agent's  service endpoint.

The pico-engine needs to be restarted with `PICO_ENGINE_HOST=https://manifold.picolabs.io:9090` and then we need to verify that two agents within this production instance can still interoperate.

**Comment by b1conrad** [comment]
Our Manifold instance has moved to a different EC2 instance.

Now, the invitations provide an endpoint that starts with http://172.18.10.145:8080 which again still works but only for other agents running in the same Manifold instance.

We still need to restart the pico engine that our Manifold instance uses, setting the `PICO_ENGINE_HOST` as shown above

**Comment by nmartinezbyu** [comment]
Should be resolved. I even tested it by making a connection.
